src/Entity/Structure.php
<?php

namespace App\Entity;

use App\Repository\StructureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=StructureRepository::class)
 * @Vich\Uploadable
 */
class Structure
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $streetNumber;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $streetName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\OneToOne(targetEntity=Type::class, inversedBy="structure", cascade={"persist", "remove"})
     */
    private $type_id;

    /**
     * @ORM\OneToMany(targetEntity=BusinessHours::class, mappedBy="structure")
     */
    private $businessHours;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="structures", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Affluence::class, mappedBy="structure")
     */
    private $affluences;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $StructureName;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $map;



    public function __construct()
    {
        $this->businessHours = new ArrayCollection();
        $this->affluences = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getStreetNumber(): ?string
    {
        return $this->streetNumber;
    }

    public function setStreetNumber(string $streetNumber): self
    {
        $this->streetNumber = $streetNumber;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->streetName;
    }

    public function setStreetName(string $streetName): self
    {
        $this->streetName = $streetName;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTypeId(): ?Type
    {
        return $this->type_id;
    }

    public function setTypeId(?Type $type_id): self
    {
        $this->type_id = $type_id;

        return $this;
    }

    /**
     * @return Collection|BusinessHours[]
     */
    public function getBusinessHours(): Collection
    {
        return $this->businessHours;
    }

    public function addBusinessHour(BusinessHours $businessHour): self
    {
        if (!$this->businessHours->contains($businessHour)) {
            $this->businessHours[] = $businessHour;
            $businessHour->setStructure($this);
        }

        return $this;
    }

    public function removeBusinessHour(BusinessHours $businessHour): self
    {
        if ($this->businessHours->removeElement($businessHour)) {
            // set the owning side to null (unless already changed)
            if ($businessHour->getStructure() === $this) {
                $businessHour->setStructure(null);
            }
        }

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile && $imageFile instanceof UploadedFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return Collection|Affluence[]
     */
    public function getAffluences(): Collection
    {
        return $this->affluences;
    }

    public function addAffluence(Affluence $affluence): self
    {
        if (!$this->affluences->contains($affluence)) {
            $this->affluences[] = $affluence;
            $affluence->setStructure($this);
        }

        return $this;
    }

    public function removeAffluence(Affluence $affluence): self
    {
        if ($this->affluences->removeElement($affluence)) {
            // set the owning side to null (unless already changed)
            if ($affluence->getStructure() === $this) {
                $affluence->setStructure(null);
            }
        }

        return $this;
    }

    public function getStructureName(): ?string
    {
        return $this->StructureName;
    }

    public function setStructureName(?string $StructureName): self
    {
        $this->StructureName = $StructureName;

        return $this;
    }

    public function getMap(): ?string
    {
        return $this->map;
    }

    public function setMap(?string $map): self
    {
        $this->map = $map;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\BusinessHours;
use App\Entity\Structure;
use App\Form\UpdateBusinessHoursType;
use App\Form\UpdateStructureInfoType;
use App\Repository\AffluenceRepository;
use App\Repository\BusinessHoursRepository;
use App\Repository\StructureRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;


class DashboardController extends AbstractController
{

    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }


    /**
     * @Route("/homePro", name="homePro")
     */
    public function homePro(){
        return $this->render('dashboard/indexPro.html.twig', [

        ]);
    }

    /**
     * @Route("/dashboard", name="dashboard")
     * @IsGranted("ROLE_ADMIN")
     * @param UserRepository $userRepository
     * @param BusinessHoursRepository $businessHoursRepository
     * @return Response
     */
    public function index(UserRepository $userRepository, BusinessHoursRepository $businessHoursRepository): Response
    {
        $idUser = $this->getUser()->getId();
        $userStructureId = $this->getUser()->getStructure();

        $userDetails = $userRepository->findBy(['id' => $idUser]);
        $businessHours = $businessHoursRepository->findBy(['structure' =>  $userStructureId]);


        return $this->render('dashboard/index.html.twig', [
            'userDetails' => $userDetails,
            'businessHours' => $businessHours
        ]);
    }

    /**
     * * @Route("/updateStructureDetails/{id}", name="update_structure_details")
     * @IsGranted("ROLE_ADMIN")
     * @param Structure $structure
     * @return RedirectResponse|Response
     */
    public function updateStructureDetails(Structure $structure, Request $req){

        $form = $this->createForm(UpdateStructureInfoType::class, $structure);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($structure);
            $this->em->flush();

            $this->addFlash('success', 'Détails de la struture bien été modifiées.');
            return $this->redirectToRoute('dashboard');
        }

        return $this->render('dashboard/updateStructureDetails.html.twig', [
            "user" => $this->getUser(),
            "form" => $form->createView()

        ]);
    }

    /**
     * @Route("/updateBusinessHours/{id}", name="update_business_hours")
     * @IsGranted("ROLE_ADMIN")
     * @param BusinessHours $businessHours
     * @param Request $req
     * @return RedirectResponse|Response
     */
    public function updateBusinessHours(BusinessHours $businessHours, Request $req){


        $businessHour = $businessHours;

        $form = $this->createForm(UpdateBusinessHoursType::class, $businessHours);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($businessHours);
            $this->em->flush();

            $this->addFlash('success', 'Horaires bien été modifiés.');
            return $this->redirectToRoute('dashboard');
        }

        return $this->render('dashboard/updateBusinessHours.html.twig', [
            "user" => $this->getUser(),
            "form" => $form->createView(),
            "businessHour" => $businessHour

        ]);
    }


    /**
     * @Route("/structure_details/{id}", name="strucuture_details_client")
     * @param AffluenceRepository $affluenceRepository
     * @param StructureRepository $structureRepository
     * @param BusinessHoursRepository $businessHoursRepository
     * @param $id
     * @return Response
     */
    public function structureDetails(AffluenceRepository $affluenceRepository, StructureRepository $structureRepository, BusinessHoursRepository $businessHoursRepository, $id){

        $structureDetails = $structureRepository->findBy(['id' => $id]);
        $buisinessDetails = $businessHoursRepository->findBy(['structure' => $id]);
        $affluencesData = ($affluenceRepository->findDataByStructureId($id));

        dump($affluencesData);



        return $this->render('dashboard/structureDetail.html.twig', [
            'structureDetails' => $structureDetails,
            'businessDetails' => $buisinessDetails,
            "affluences" => $affluencesData

        ]);

    }

}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Dashboard {% endblock %}
{% block body %}
    <div class="container-fluid mt-4 container--dashboard">
            <div class="row">
                <div class="col-2" style="border-right: 1px solid black;">

                    <h2>FLOW</h2>
                    <h5>Espace Professionnels</h5>
                    <nav class="nav flex-column mt-4">
                        <a class="nav-link" href="{{ path('home') }}">Site client</a>
                        <a class="nav-link" href="{{ path('dashboard') }}">Infos pratiques</a>
                        <a class="nav-link" href="{{ path('affluence_dashboard') }}">Taux d'affluence</a>
                        <a class="nav-link" href="#">Contact</a>
                        <hr>
                        <a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
                    </nav>
                </div>
                <div class="col-8">
                    {% for detail in userDetails %}
                    <h1>Bonjour, {{ detail.compagnyName }}</h1>
                    <h6>Bienvenue sur votre espace d'administration</h6>
                        {%  for message in app.flashes('success') %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                               {{message}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}

                        <div class="text-center mt-5">
                            <img src="/images/structures/{{ detail.structure.imageName }}" class="img-fluid" height="80" alt="imageStructuyre" >
                        </div>

                     <h5 class="mb-4 mt-5">Les infos pratiques de votre structure <div class="d-inline"><a type="button" class="btn btn-primary" href="{{ path('update_structure_details', {id: detail.structure.id}) }}">Modifier</a></div></h5>
                      <p>Téléphone : {{ detail.structure.phone }} </p>
                      <p>
                          Adresse :
                          {{ detail.structure.streetNumber }},
                          {{ detail.structure.streetName }}
                          {{ detail.structure.zipCode }}
                          {{ detail.structure.city }} -  {{ detail.structure.country }}
                      </p>

                        <h5 class="mb-4 mt-5">Les horaires de votre structure </h5>
                    {% endfor %}
                    {% for businessHour in businessHours %}
                        {% if businessHour.day == 1 %}
                            <p class="font-weight-bold">Lundi :
                                    <span class="font-weight-light">
                                        {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                    <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                                    </span>
                            </p>
                        {% elseif businessHour.day == 2 %}
                            <p class="font-weight-bold">Mardi :
                                <span class="font-weight-light">
                                    {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                    <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                                </span> </p>
                        {% elseif businessHour.day == 3 %}
                        <p class="font-weight-bold">Mercredi :
                            <span class="font-weight-light">
                                {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                            </span>
                        </p>
                        {% elseif businessHour.day == 4 %}
                        <p class="font-weight-bold">Jeudi :
                            <span class="font-weight-light">
                                {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                            </span>
                        </p>
                        {% elseif businessHour.day == 5 %}
                            <p class="font-weight-bold">Vendredi :
                                <span class="font-weight-light">
                                    {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                    <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                                </span>
                            </p>
                       <hr>
                        {% elseif businessHour.day == 6 %}
                            <p class="font-weight-bold">Samedi :
                                <span class="font-weight-light">
                                    {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                    <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                                </span>
                            </p>
                        {% elseif businessHour.day == 7 %}
                                <p class="font-weight-bold">Dimanche :
                                    <span class="font-weight-light">
                                        {{ businessHour.openTime }} | {{ businessHour.closeTime }}
                                        <a type="button" class="btn btn-primary" href="{{ path('update_business_hours', {id: businessHour.id}) }}"><img src="{{ asset('assets/img/crayon.svg') }}" width="18"></a>
                                    </span>
                                </p>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
    </div>
    <div class="container-fluid mt-5 sticky-bottom" style="padding-left: 0px; padding-right: 0px;">
        <footer class="footer p-3 " style="border-top: solid 1px black">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Copyright © Flow 2020</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <a class="mr-3" href="#!">Mentions légales</a>
                        <a href="#!">Politique de confidentialités</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

templates/dashboard/resulat.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}

<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{{ asset('assets/img/diagram.svg') }}"  alt="" /></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ml-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">A propos</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger font-weight-bold" href="{{ path('homePro') }}">Espace Pro</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading text-uppercase ">Résultats de votre recherche</div>
    </div>

</header>

        <div class="text-center mt-5">
            <h2>{{ message }}</h2>
        </div>

    <section style="padding-top: 10px;">
        <div class="row">
            <div class="offset-3 col-6">
                <h5 class="text-center">Nouvelle recherche</h5>

                {{ form_start(form) }}
                <div class="row">
                    <div class="col-10">
                        {{ form_row(form.name) }}
                    </div>
                    <div class="2">
                        <button class="btn btn-warning ml-1" type="submit">Rechercher</button>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>


    <div class="mt-5 offset-2 col-10">
        {% for result in results  %}
        <div class="col-2">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="/images/structures/{{ result.structure.imageName }}" alt="Card image cap">

                <div class="card-body">

                    <h5 class="card-title text-center mb-3"> {{ result.compagnyName }}</h5>
                    <hr>
                    <p class="card-text"> <span><i class="fas fa-phone"></i></span> {{ result.structure.phone }}</p>
                    <p> <span><i class="fas fa-map-marker-alt"></i></span>
                        {{ result.structure.streetNumber }},
                        {{ result.structure.streetName }}
                        {{ result.structure.zipCode }}
                        {{ result.structure.city }} -  {{ result.structure.country }}
                    </p>
                </div>

                <div class="card-body text-center">
                    <a type="button" class="btn btn-primary" href="{{ path('strucuture_details_client', {id: result.structure.id}) }}">Plus d'infos</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    </section>











{% endblock %}

templates/dashboard/structureDetail.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script>

        const options = {
            chart: {
                type: 'heatmap'
            },
            plotOptions: {
                heatmap: {
                    colorScale: {
                        ranges: [{
                            from: 0,
                            to: 50,
                            color: '#4feaff',
                            name: 'Peu de  visiteurs',
                        },
                            {
                                from: 50,
                                to: 200,
                                color: '#2986c4',
                                name: 'Niveau intermédiare',
                            },
                            {
                                from: 200,
                                to:500,
                                color: '#144299',
                                name: 'Beaucoup de visiteurs',
                            }
                        ]
                    }
                }
            },
            series: [
                {% set day = null %}
                {%- for affluence in affluences   -%}
                {%- if not loop.first and affluence.startTime|date('l') != day -%}
                {{ "]}"|raw }}
                {%- if not loop.last -%}
                {{ ',' }}
                {%- endif -%}
                {%- endif -%}
                {%- if affluence.startTime|date('l') != day -%}
                {{ ("{name: '" ~ affluence.startTime|date('d/m/Y') ~ "', data: [")|raw }}
                {%- endif -%}
                {{ ("{x: '" ~ affluence.startTime|date('H\\h') ~ "-" ~ affluence.endTime|date('H\\h') ~ "',  y: " ~ affluence.numberOfPeople ~ "},")|raw }}

                {% if loop.last %}
                {{ "]}"|raw }}
                {% endif %}

                {% set day = affluence.startTime|date('l') %}
                {%- endfor -%}
            ]
        };



        const chart = new ApexCharts(document.querySelector("#chart"), options);

        chart.render();



    </script>
{% endblock %}

{% block body %}

<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="assets/img/diagram.svg"  alt="" /></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ml-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">A propos</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger font-weight-bold" href="{{ path('homePro') }}">Espace Pro</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- Masthead-->
{% for detail in structureDetails %}
<header class="masthead">
    <div class="container">
        <div class="masthead-heading text-uppercase " style="margin-bottom: 2px;">
            {{ detail.structureName }}
        </div>
        <div class="masthead-subheading text-uppercase " style="margin-top:0px;">
            {{ detail.city }}
        </div>
    </div>
</header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 text-center" style="margin-top:-180px; margin-bottom: 30px">
                <img src="/images/structures/{{ detail.imageName }}" class="img-fluid" height="80" alt="imageStructure" style="  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);" >
            </div>

        </div>

    </div>

    <div class="container-fluid">
        <div class="text-center">
            <h2 class="mb-3">Les horaires</h2>
            <div class="row text-center justify-content-center mb-4">
                {% for businessHour in businessDetails %}
                    {% if businessHour.day == 1 %}
                <div class="col-1">
                    <span class="font-weight-bold">Lundi</span><br>
                    <span> {{ businessHour.openTime }} </span><br>
                    <span>{{  businessHour.closeTime }}</span>
                </div>
                    {% elseif businessHour.day == 2 %}
                <div class="col-1">
                    <span class="font-weight-bold">Mardi</span><br>
                    <span> {{ businessHour.openTime }} </span><br>
                    <span>{{  businessHour.closeTime }}</span>
                </div>
                {% elseif businessHour.day == 3 %}
                    <div class="col-1">
                        <span class="font-weight-bold">Mercredi</span><br>
                        <span> {{ businessHour.openTime }} </span><br>
                        <span>{{  businessHour.closeTime }}</span>
                    </div>
                {% elseif businessHour.day == 4 %}
                    <div class="col-1">
                        <span class="font-weight-bold">Jeudi</span><br>
                        <span> {{ businessHour.openTime }} </span><br>
                        <span>{{  businessHour.closeTime }}</span>
                    </div>
                {% elseif businessHour.day == 5 %}
                    <div class="col-1">
                        <span class="font-weight-bold">Vendredi</span><br>
                        <span> {{ businessHour.openTime }} </span><br>
                        <span>{{  businessHour.closeTime }}</span>
                    </div>
                {% elseif businessHour.day == 6 %}
                    <div class="col-1">
                        <span class="font-weight-bold">Samedi</span><br>
                        <span> {{ businessHour.openTime }} </span><br>
                        <span>{{  businessHour.closeTime }}</span>
                    </div>
                {% elseif businessHour.day == 7 %}
                    <div class="col-1">
                        <span class="font-weight-bold">Dimanche</span><br>
                        <span> {{ businessHour.openTime }} </span><br>
                        <span>{{  businessHour.closeTime }}</span>
                    </div>
                {% endif %}


                {% endfor %}
            </div>
            <h2 class="mt-5 mb-3">L'affluence ces derniers jours</h2>
            <div  class="offset-2 col-8" id="chart">
            </div>

            <h2 class="mb-4 mt-5">Informations pratiques</h2>
            <div class="row justify-content-center mb-5">
                <div class="col-4">
                    <h5>Nous contacter</h5>
                    <span><i class="fa fa-phone" aria-hidden="true"></i> {{ detail.phone }}</span>
                </div>
                <div class="col-4">
                    <h5>Adresse</h5>
                    <span>
                        {{ detail.streetNumber }},
                        {{ detail.streetName }}
                        {{ detail.zipCode }}
                        {{ detail.city }} -  {{ detail.country }}
                    </span>
                </div>
            </div>

            <iframe src="{{ detail.map }}" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>


        </div>
    </div>

    <div class="container-fluid mt-4 sticky-bottom" style="padding-left: 0px; padding-right: 0px;">
        <footer class="footer p-3 ">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Copyright © Flow 2020</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-right">
                        <a class="mr-3" href="#!">Mentions légales</a>
                        <a href="#!">Politique de confidentialités</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
{% endfor %}


{% endblock %}